name: Doxygen

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.4

    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@1.9.8
      # with:
      #   doxyfile-path: './Doxyfile'
      #   working-directory: '.'

    - name: Deploy on GitHub Pages
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html