name: Doxygen

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.4

    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@1.9.8
      with:
        working-directory: 'src'
        doxyfile-path: 'doxyfile'

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: src
        token: ${{ secrets.GITHUB_TOKEN }}